---
apiVersion: v2
name: netbird
description: NetBird VPN management platform
type: application
version: 1.7.0
appVersion: "0.41.3"
icon: https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/kuu5tm1wt09ztp6ctlag
